spring:
  datasource:
    username: root
    password: kate110276
    url: jdbc:mysql://localhost:3306/inventory_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: inventory-service

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

